name: Cut Release
on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go caches
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.RELEASE_SSH_KEY }} | base64 -d > ~/.ssh/id_ed25519
          ssh-keyscan git.gitea.svc.alrest.xeserv.us >> ~/.ssh/known_hosts
        env:
          RELEASE_SSH_KEY: ${{ secrets.RELEASE_SSH_KEY }}

      - name: release
        env:
          GITEA_TOKEN: ${{ secrets.RELEASE_GITEA_TOKEN }}
          GITEA_URL: https://git.xeserv.us
        run: |
          npm ci
          npx semantic-release
